descriptor-schema-version: "2.2"
info:
  name: iox19
  version: latest
app:
  cpuarch: ppc
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: 50
    disk: 2
    memory: 64
    network:
    - interface-name: eth0
      ports: {}
    profile: custom
  startup:
    rootfs: rootfs.ext4
    target:
    - /bin/sh
    - /usr/local/bin/sleep.sh
  type: docker
